job:
    path:     /
    defaults: { _controller: "SpleenJobeetBundle:Job:index" }

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "SpleenJobeetBundle:Job:show" }
    requirements:
        id: \d+
        
job_preview:
    path:     /{company}/{location}/{token}/{position}
    defaults: { _controller: "SpleenJobeetBundle:Job:preview" }
    requirements:
        id: \w+

job_new:
    path:     /new
    defaults: { _controller: "SpleenJobeetBundle:Job:new" }

job_create:
    path:     /create
    defaults: { _controller: "SpleenJobeetBundle:Job:create" }
    methods:  POST

job_edit:
    path:     /{token}/edit
    defaults: { _controller: "SpleenJobeetBundle:Job:edit" }

job_update:
    path:     /{token}/update
    defaults: { _controller: "SpleenJobeetBundle:Job:update" }
    methods:  [POST, PUT]

job_delete:
    path:     /{token}/delete
    defaults: { _controller: "SpleenJobeetBundle:Job:delete" }
    methods:  [POST, DELETE]

job_publish:
    path:     /{token}/publish
    defaults: { _controller: "SpleenJobeetBundle:Job:publish" }
    methods:  [POST]
